name: Pages
on:
  pull_request:
    branches: [ main ]   # PRではビルドのみ
  push:
    branches: [ main ]   # マージ後に本番デプロイ

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      # ここでJekyll等のビルド
      - uses: actions/upload-pages-artifact@v4  # PRでもOK（アップロードだけ）
        with:
          path: docs/_site

  deploy:
    if: github.event_name == 'push'   # ← PRでは走らない
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
